---
# Playbook to create database in Filestore

- name: Create Database in Filestore
  hosts: localhost
  gather_facts: false
  environment:
    GOOGLE_CREDENTIALS: "{{ gcp_cred_file }}"
  roles:
      - ghost_db_create
      