---
# Playbook to deploy Ghost and its components

- name: Deploy Ghost
  hosts: localhost
  gather_facts: false
  environment:
    GOOGLE_CREDENTIALS: "{{ gcp_cred_file }}"
  roles:
      - ghost_db_create
      - ghost_app_deploy
      


