apiVersion: v1
kind: Deployment
metadata:
  name: postfix
  namespace: ascn-cluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postfix
  template:
    metadata:
      labels:
        app: postfix
    spec:
      containers:
      - name: postfix
        image: webdevops/postfix
        env:
          - name: MYHOSTNAME
            value: ascn_g28.com
          - name: MAILNAME
            value: ascn_g28.com
          - name: MYNETWORKS
            value: "127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128"
          - name: SMTP_USE_TLS
            value: "yes"
