- name: Create k8s namespace
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1 
      kind: Namespace
      metadata:
        name: ascn-cluster

- name: Postfix deployment
  kubernetes.core.k8s:
    state: present
    src: containers/postfix/postfix-deployment.yml

- name: Postfix service 
  kubernetes.core.k8s:
    state: present
    src: containers/postfix/postfix-service.yml