- name: Create k8s namespace
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1 
      kind: Namespace
      metadata:
        name: ascn-cluster

- name: Ghost deploymxent
  kubernetes.core.k8s:
    state: present
    src: containers/ghost/ghost_deployment.yml

- name: Ghost service 
  kubernetes.core.k8s:
    state: present
    src: containers/ghost/ghost_service.yml