- name: Create k8s namespace
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1 
      kind: Namespace
      metadata:
        name: ascn-cluster

- name: Ghost deployment
  kubernetes.core.k8s:
    state: present
    src: containers/ghost/ghost_deployment.yml

- name: Ghost service 
  kubernetes.core.k8s:
    state: present
    src: containers/ghost/ghost_service.yml

- name: Get MySQL Pod Name
  shell: kubectl get pods -l app=mysql -o jsonpath='{.items[0].metadata.name}'
  register: mysql_pod_name

- name: Create Ghopt Admin
  shell: kubectl exec -it {{ mysql_pod_name.stdout_lines[0] }} -- mysql -u ghostuser -p'Gh0$t' -e "USE ghost; update users set name='ascn', password='\$2b\$10\$p.omuFaYklAoyjMzfvmKT.rbL64WVej1aIub.em0rSG20LbRE2S1y', email='ascn@example.com', status='active' where id=1;"