---
# Service for exposing MySQL
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: ascn-cluster
  labels:
    app: mysql
    tier: database
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
    - targetPort: 3306 # port that containers are listening on
      port: 3306 # port number exposed internally in the cluster